name: Build Engine DLLs

on:
  push:
    branches: [ "NetStandard" ]
  pull_request:
    branches: [ "NetStandard" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout FRB
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        path: 'FlatRedBall'
        submodules: recursive

    - name: Checkout Gum
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/Gum
        fetch-depth: 1
        path: 'Gum'

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build FlatRedBall iOS .NET 8
      run: dotnet build -c ${{ matrix.configuration }} 'FlatRedBall\Engines\Forms\FlatRedBall.Forms\FlatRedBall.Forms.iOS.Net8.sln'
    - name: Package FlatRedBall iOS .NET 8
      uses: actions/upload-artifact@v3
      with:
        name: iOSMonoGameNet8${{ matrix.configuration }}
        path: FlatRedBall\Engines\Forms\FlatRedBall.Forms\FlatRedBall.Forms.iOSMonoGame\bin\${{ matrix.configuration }}\net8.0-ios\

    - name: Build FlatRedBall Android .NET 8
      run: dotnet build -c ${{ matrix.configuration }} 'FlatRedBall\Engines\Forms\FlatRedBall.Forms\FlatRedBall.Forms.Android.Net8.sln'
    - name: Package FlatRedBall Android .NET 8
      uses: actions/upload-artifact@v3
      with:
        name: AndroidMonoGameNet8${{ matrix.configuration }}
        path: FlatRedBall\Engines\Forms\FlatRedBall.Forms\FlatRedBall.Forms.AndroidMonoGame\bin\${{ matrix.configuration }}\net8.0-android\

    - name: Build FlatRedBall FNA .NET 7
      run: dotnet build -c ${{ matrix.configuration }} 'FlatRedBall\Engines\Forms\FlatRedBall.Forms\FlatRedBall.Forms.FNA.sln'
    - name: Package FlatRedBall FNA .NET 7
      uses: actions/upload-artifact@v3
      with:
        name: DesktopGlFnaNet7${{ matrix.configuration }}
        path: FlatRedBall/Engines/Forms/FlatRedBall.Forms/FlatRedBall.Forms.FNA/bin/${{ matrix.configuration }}/net7.0/

    - name: Build FlatRedBall .NET 6
      run: dotnet build -c ${{ matrix.configuration }} 'FlatRedBall\Engines\Forms\FlatRedBall.Forms\FlatRedBall.Forms.DesktopGLNet6.sln'
    - name: Package FlatRedBall .NET 6
      uses: actions/upload-artifact@v3
      with:
        name: DesktopGlNet6${{ matrix.configuration }}
        path: FlatRedBall/Engines/Forms/FlatRedBall.Forms/FlatRedBall.Forms.DesktopGlNet6/bin/${{ matrix.configuration }}/net6.0/

    - name: Build FlatRedBall .NET 4
      run: dotnet build -c ${{ matrix.configuration }} 'FlatRedBall\Engines\Forms\FlatRedBall.Forms\FlatRedBall.Forms.DesktopGL.sln'
    - name: Package FlatRedBall .NET 4
      uses: actions/upload-artifact@v3
      with:
        name: DesktopGlNet4${{ matrix.configuration }}
        path: FlatRedBall/Engines/Forms/FlatRedBall.Forms/FlatRedBall.Forms/bin/DesktopGL/${{ matrix.configuration }}/

  gatekeeper:
    needs: [build]
    runs-on: windows-latest
    steps:
      - name: Trigger next jobs
        run: echo "All build jobs completed successfully."

  copyBuildsToTemplates:
    needs: [gatekeeper]
    env:
      TEMPLATES: FlatRedBall\Templates
      FORMS: FlatRedBall\Engines\Forms\FlatRedBall.Forms
    runs-on: windows-latest
    steps:
      - name: Copy libs
        run: |
          xcopy /E /I "${{ env.FORMS }}\FlatRedBall.Forms\bin\DesktopGL\Debug\*" ${{ env.TEMPLATES }}\FlatRedBallDesktopGlTemplate\FlatRedBallDesktopGlTemplate\Libraries\DesktopGl\Debug
          xcopy /E /I "${{ env.FORMS }}\FlatRedBall.Forms\bin\DesktopGL\Release\*" ${{ env.TEMPLATES }}\FlatRedBallDesktopGlTemplate\FlatRedBallDesktopGlTemplate\Libraries\DesktopGl\Release
