name: FlatRedBall Editor

on:
  push:
    branches: [ "NetStandard" ]
  pull_request:
    branches: [ "NetStandard" ]

jobs:
  build:
    strategy:
      matrix:
        # configuration: [Debug, Release]
        # for now, let's just do debug...
        configuration: [Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout FRB
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        path: 'FRB'

    - name: Checkout Gum
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/Gum
        fetch-depth: 1
        path: 'Gum'

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: dotnet build -c ${{ matrix.configuration }} 'FRB\FRBDK\Glue\Glue with All.sln'

    - name: Build BuildServerUploader
      run: dotnet build -c Debug 'FlatRedBall\FRBDK\BuildServerUploader\BuildServerUploader.sln'

      
    - name: Zip and upload templates
      env: # Or as an environment variable
        username: ${{ secrets.FTPUSERNAME }}
        password: ${{ secrets.FTPPASSWORD }}
      run: .\FlatRedBall\FRBDK\BuildServerUploader\BuildServerUploaderConsole\bin\x86\Debug\BuildServerUploaderConsole.exe zipanduploadfrbdk "${{ env.username }}" "${{ env.password }}"

    - name: Package
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.configuration }}
        path: FRB/FRBDK/Glue/Glue/bin/${{ matrix.configuration }}
